version: '3.3'

services:

  k3s-server-1:
    image: rancher/k3s:v1.30.3-k3s1
    container_name: k3s-server-1
    hostname: k3s-server-1
    privileged: true
    restart: always
    environment:
      - K3S_KUBECONFIG_OUTPUT=/mnt/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - $DATA_DIR:/root/.titancandidate

      - $K3S_DATA_DIR/server:/var/lib/rancher/k3s
      - $K3S_DATA_DIR/output:/mnt/output
      - $K3S_DATA_DIR/etc:/etc/rancher/k3s
      - $K3S_DATA_DIR/secrets:/var/run/secrets
      - $K3S_DATA_DIR/storage:/mnt/storage
    ports:
      - 80:80/tcp
      - 443:443/tcp
    command:
      - server
      - "--disable=traefik"
      - "--https-listen-port=6443"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: ["CMD-SHELL", "kubectl get nodes || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s


  aron-titan-l1:
    image: aron666/aron-titan-l1
    container_name: aron-titan-l1
    environment:
      TITAN_NETWORK_LOCATORURL: ${TITAN_NETWORK_LOCATORURL:-"https://cassini-locator.titannet.io:5000/rpc/v0"}
      TITAN_EDGE_BINDING_URL: ${TITAN_EDGE_BINDING_URL:-"https://api-test1.container1.titannet.io/api/v2/device/binding"}
      TITAN_L1_CODE: ${TITAN_L1_CODE}
      TITAN_EDGE_ID: ${TITAN_EDGE_ID}
      KUBECONFIG: "/mnt/output/kubeconfig.yaml"
      KUBERNETES_SERVICE_HOST: "k3s-server-1"
      KUBERNETES_SERVICE_PORT: "6443"
    privileged: true
    ports:
      - 2345:2345/tcp
      - 2345:2345/udp
      - 9000:9000/tcp
    volumes:
      - $DATA_DIR:/root/.titancandidate
      - $K3S_DATA_DIR/output:/mnt/output
      - $K3S_DATA_DIR/secrets:/var/run/secrets
      - $K3S_DATA_DIR/flags:/mnt/flags
    restart: always